version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/envios_db
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm start
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend:
    build:
      context: ../Envios_Front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
    driver: local